name: dartactyl
description: An API client wrapper for Pterodactyl Panel. Following V1 for now.
repository: https://github.com/TekExplorer/dartactyl/
version: 1.7.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.0 <3.0.0'
 
dependencies:
  dio: ^5.0.0
  freezed_annotation: ^2.0.3
  html: ^0.15.0
  json_annotation: ^4.8.0
  meta: ^1.7.0
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  universal_io: ^2.0.4
  web_socket_channel: ^2.3.0

dev_dependencies:
  build_runner: '>=2.3.0 <4.0.0' 
  freezed: ^2.0.3+1
  json_serializable: ^6.0.1
  lints: ^2.0.0
  mocktail: ^0.3.0
  mocktailx: ^0.0.3
  retrofit_generator: ^5.0.0
  source_gen: ^1.2.1
  stream_channel: ^2.1.1
  test: ^1.20.2
  very_good_analysis: ^4.0.0+1
