name: dartactyl
description: An API client for Pterodactyl Panel
repository: https://github.com/TekExplorer/dartactyl/
version: 1.0.2
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_value: ^8.1.3
  dio: ^4.0.1
  json_annotation: ^4.3.0
  retrofit: ^2.0.1

dev_dependencies:
  build_runner: any
  built_value_generator: any
  json_serializable: 6.0.1
  lints: ^1.0.0
  retrofit_generator: any
  # test: ^1.16.0
