name: dartactyl
description: An API client wrapper for Pterodactyl Panel. Following V1 for now.
repository: https://github.com/TekExplorer/dartactyl/
version: 1.11.1
# homepage: https://www.example.com
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dio: ^5.0.0
  fast_immutable_collections: ^10.2.4
  freezed_annotation: ^2.4.1
  html: ^0.15.0
  json_annotation: ^4.9.0
  meta: ^1.7.0
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  universal_io: ^2.0.4
  web_socket: ^0.1.6

dev_dependencies:
  analyzer: ^6.0.0
  build_runner: '>=2.4.7 <4.0.0'
  freezed: ^2.4.5
  json_serializable: '>=6.7.0'
  lints: ^4.0.0
  mocktail: ^1.0.1
  mocktailx: ^0.0.3
  retrofit_generator: ^8.0.4
  source_gen: ^1.2.1
  stream_channel: ^2.1.1
  test: ^1.20.2
  very_good_analysis: ^5.1.0
