name: dartactyl
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_value: any
  dio: any
  json_annotation: any
  logger: ^1.0.0
  retrofit: any

dev_dependencies:
  build_runner: any
  built_value_generator: any
  json_serializable: any
  lints: ^1.0.0

  retrofit_generator: any
  test: ^1.16.0
