name: dartactyl
description: An API client wrapper for Pterodactyl Panel. Following V1 for now.
repository: https://github.com/TekExplorer/dartactyl/
version: 1.6.6
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.0 <3.0.0'
 
dependencies:
  bloc: ^8.0.3
  dio: ^4.0.1
  freezed_annotation: ^2.0.3
  html: ^0.15.0
  json_annotation: ^4.7.0
  meta: ^1.7.0
  retrofit: ^3.3.1
  universal_io: ^2.0.4

dev_dependencies:
  freezed: ^2.0.3+1
  json_serializable: ^6.0.1
  lints: ^2.0.0
  source_gen: ^1.2.1
  test: ^1.20.2
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0' 
