name: dartactyl
description: An API client wrapper for Pterodactyl Panel. Following V1 for now.
repository: https://github.com/TekExplorer/dartactyl/
version: 1.4.0-dev.20
# homepage: https://www.example.com
environment:
  sdk: '>=2.14.0 <3.0.0'
 
dependencies:
  bloc: ^8.0.3
  dio: ^4.0.1
  freezed_annotation: ^1.1.0
  html: ^0.15.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  retrofit: ^3.0.1+1
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: any
  built_value_generator: any
  freezed: ^1.1.1
  json_serializable: ^6.0.1
  lints: ^1.0.0
  retrofit_generator: ^4.0.1
  source_gen: ^1.2.1
  test: ^1.20.2
